ALTER TABLE CONTASRECEBER ADD NSU VARCHAR(15);
ALTER TABLE CONTASRECEBER ADD AUTORIZACAO INTEGER;
ALTER TABLE CONTASRECEBER ADD TAXA_OPERADORA NUMERIC(15,2);
ALTER TABLE CONTASRECEBER ADD VALOR_LIQUIDO NUMERIC(15,2);