CREATE TABLE LOCAL_TRIBUTACAO (
    ID_LOCALTRIBUTACAO  INTEGER NOT NULL,
    CODIGO              VARCHAR(10),
    DESCRICAO           VARCHAR(100)
);

ALTER TABLE LOCAL_TRIBUTACAO ADD CONSTRAINT PK_LOCAL_TRIBUTACAO PRIMARY KEY (ID_LOCALTRIBUTACAO);
