CREATE TABLE CONFIG_SERVICO (
    ID                INTEGER NOT NULL,
    EMPRICOD          INTEGER,
    SERIA5COD         CHAR(5),
    ID_TRIBUTACAO     INTEGER,
    LOCAL_TRIBUTACAO  INTEGER
);

ALTER TABLE CONFIG_SERVICO ADD CONSTRAINT PK_CONFIG_SERVICO PRIMARY KEY (ID);
