ALTER TABLE CUPOMITEM ADD ALIQUOTA_PIS NUMERIC(15,2);
ALTER TABLE CUPOMITEM ADD VLR_BASE_PIS NUMERIC(15,2);
ALTER TABLE CUPOMITEM ADD ALIQUOTA_COFINS NUMERIC(15,2);
ALTER TABLE CUPOMITEM ADD VLR_BASE_COFINS NUMERIC(15,2);