SET TERM ^ ;

create or alter procedure SP_BUSCAR_MOV_CAIXA (
    CUPOA13ID varchar(30))
returns (
    VALOR numeric(15,3))
as
declare variable VALOR_JUROS numeric(15,3);
declare variable VALOR_MULTA numeric(15,3);
declare variable VALOR_JUROS_PAGO numeric(15,3);
declare variable VALOR_MULTA_PAGA numeric(15,3);
BEGIN
    FOR SELECT SUM(COALESCE(A.MVCXN2VLRJURO, 0)), SUM(COALESCE(A.MVCXN2VLRMULTA, 0))
        FROM MOVIMENTOCAIXA A
        LEFT JOIN OPERACAOCAIXA B ON B.OPCXICOD = A.OPCXICOD
        WHERE B.OPCXA5SIGLA = 'RCCRD'
        AND A.MVCXN2VLRCRED = 0
        AND A.MVCXA15DOCORIG LIKE :CUPOA13ID||'%'
    INTO :VALOR_JUROS, :VALOR_MULTA DO
    BEGIN

    FOR SELECT sum(coalesce(A.MVCXN2VLRCRED, 0))
        FROM MOVIMENTOCAIXA A
        LEFT JOIN OPERACAOCAIXA B ON B.OPCXICOD = A.OPCXICOD
        WHERE B.OPCXA5SIGLA = 'JURRC'
        AND A.MVCXA15DOCORIG LIKE :CUPOA13ID||'%'
    INTO :VALOR_JUROS_PAGO DO BEGIN END

    FOR SELECT sum(coalesce(MVCXN2VLRCRED, 0))
        FROM MOVIMENTOCAIXA A
        LEFT JOIN OPERACAOCAIXA B ON B.OPCXICOD = A.OPCXICOD
        WHERE B.OPCXA5SIGLA = 'MULRC'
        AND A.MVCXA15DOCORIG LIKE :CUPOA13ID||'%'
    INTO :VALOR_MULTA_PAGA DO BEGIN END

    VALOR_JUROS      = COALESCE(VALOR_JUROS, 0);
    VALOR_JUROS_PAGO = COALESCE(VALOR_JUROS_PAGO, 0);
    VALOR_MULTA      = COALESCE(VALOR_MULTA, 0);
    VALOR_MULTA_PAGA = COALESCE(VALOR_MULTA_PAGA, 0);

    --VALOR = (VALOR_JUROS - VALOR_JUROS_PAGO) + (VALOR_MULTA - VALOR_MULTA_PAGA);
    VALOR = VALOR_JUROS + VALOR_MULTA;

    SUSPEND;
  END
END^

SET TERM ; ^

/* Following GRANT statetements are generated automatically */

GRANT SELECT ON MOVIMENTOCAIXA TO PROCEDURE SP_BUSCAR_MOV_CAIXA;
GRANT SELECT ON OPERACAOCAIXA TO PROCEDURE SP_BUSCAR_MOV_CAIXA;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE SP_BUSCAR_MOV_CAIXA TO PUBLIC;
GRANT EXECUTE ON PROCEDURE SP_BUSCAR_MOV_CAIXA TO SYSDBA;