CREATE OR ALTER VIEW V_NOTA_SERVICO(
    CFIL,
    DESCRICAO_SERVICO,
    CID,
    EST,
    BISS,
    VISS,
    CSSL,
    VIRF,
    VINSS,
    VCOF,
    VPIS,
    VDES,
    VNOT,
    OBS,
    SER,
    DEMI,
    NNOT,
    COD_CADCLI,
    AISS,
    AIRF,
    ACSLL,
    ACOF,
    APIS,
    AINSS,
    COD,
    NATUREZA_OPERACAO,
    ISS_RETIDO,
    CIDADE_TOMADOR,
    UF_TOMADOR,
    MES_COMPETENCIA,
    ANO_COMPETENCIA,
    COD_SERVICO,
    NOME_SERVICO)
AS
SELECT
  A.SERIE, CAST(A.DESCRICAO_SERVICO AS VARCHAR(2000)), B.CLIEA60CIDRES, B.CLIEA2UFRES,
  A.BASE_CALCULO_ISS AS BISS, A.ALIQUOTA_ISS AS VISS, A.VALOR_CSSL AS CSSL,
  A.VALOR_IRPJ AS VIRF, A.VALOR_INSS AS VINSS, A.VALOR_COFINS AS VCOF, A.VALOR_PIS AS VPIS, A.VALOR_DEDUCAO AS VDES,
  A.VALOR_TOTAL AS VNOT, A.OBS, A.SERIE AS SER, A.DATA_EMISSAO AS DEMI, A.NUMERO_NOTA AS NNOT, B.CLIEA13ID AS COD_CADCLI,
  A.ALIQUOTA_ISS AS ISSQN_ALIQUOTA, 0 IRRF_ALIQUOTA, A.VALOR_CSSL, A.VALOR_COFINS, A.VALOR_PIS, A.VALOR_INSS,
  A.ID,
  '2' AS NATUREZA_OPERACAO, A.ISS_RETIDO, A.MUNICIPIO_PRESTACAO, A.UF_PRESTACAO, EXTRACT(MONTH FROM A.DATA_EMISSAO) MES_COMPETENCIA,
  EXTRACT(YEAR FROM A.DATA_EMISSAO) AS ANO_COMPETENCIA,
  C.NOME_SERVICO, CAST(C.DESCRICAO_SERVICO AS VARCHAR(2000))
FROM NOTASERVICO A
INNER JOIN CLIENTE B ON B.CLIEA13ID = A.CLIEA13ID
INNER JOIN SERVICO C ON C.ID_SERVICO = A.ID_SERVICO
;
